use_frameworks!

platform :ios, '8.0'

target 'PXPersonPrefrenceCatogeryKit_Example' do
  pod 'PXPersonPrefrenceCatogeryKit', :path => '../'

  target 'PXPersonPrefrenceCatogeryKit_Tests' do
    inherit! :search_paths

    
  end
end
